name: Periodic HealthCheck

on:
  push:
    branches:
      - main

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check pokedex health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-ne3o.onrender.com/health|https://full-stack-open-pokedex-ne3o.onrender.com/|https://full-stack-open-pokedex-ne3o.onrender.com/pokemon/bulbasaur
          max-attempts: 3
          retry-delay: 5s