name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm ci  

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: e2e Test
        run: npm run test:e2e

      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Fail
        uses: stegzilla/discord-notify@v2
        if: failure()
        with:
          title: Failure
          color: #FF3333
          message: "${{ github.event.commits[0].url }}\n by **${{ github.event.commits[0].author.name }}** broke the build"
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Success
        uses: stegzilla/discord-notify@v2
        if: success()
        with:
          title: Success
          color: #1DC249
          message: A new version of pokedex deployed
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Fail
        uses: stegzilla/discord-notify@v2
        if: failure()
        with:
          title: Failure
          color: #FF3333
          message: "${{ github.event.commits[0].url }}\n by **${{ github.event.commits[0].author.name }}** broke the build"
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
